#ddev-generated
hooks:
  pre-start:
    - exec-host: |
        # Check to see if our config flag file is present
        if [ -f ~/.ddev/1password_enabled ]; then
          echo "1Password integration enabled."
          if [ ! -f ./.ddev/docker-compose.1password.yaml ]; then
            echo "Adding 1Password docker-compose file to project."
            cat <<EOF > ./.ddev/docker-compose.1password.yaml
            #ddev-generated
            services:
              web:
                volumes:
                  - type: bind
                    source: /run/host-services/ssh-auth.sock
                    target: /run/host-services/ssh-auth.sock
                environment:
                  - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
        EOF
          fi
        else
          echo "1Password integration disabled."
            if [ -f ./.ddev/docker-compose.1password.yaml ]; then
                // Check that the file contains '#ddev-generated' to avoid deleting non-ddev files
                if grep -q '#ddev-generated' ./.ddev/docker-compose.1password.yaml; then
                    echo "Removing 1Password docker-compose file from project."
                    rm ./.ddev/docker-compose.1password.yaml
                fi
            fi
        fi
  post-start:
    - exec: "sudo chmod o+rw /run/host-services/ssh-auth.sock"
